version: "3"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    tty: true
    stdin_open: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    restart: always

  ks01:
    image: docker.elastic.co/kibana/kibana:8.3.3
    tty: true
    stdin_open: true
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    restart: always
    depends_on:
      - es01

  ls01:
    image: docker.elastic.co/logstash/logstash:8.3.3
    tty: true
    stdin_open: true
    ports:
      - "514:514"
      - "514:514/udp"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/syslog.conf:/usr/share/logstash/pipeline/syslog.conf
    restart: always
    depends_on:
      - es01

volumes:
  data:
